# Generated by Django 4.0.3 on 2022-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infohabrs',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
